plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

packageExtensions:
  'local-pkg@^0.4.3':
    peerDependencies:
      'jsdom': 'npm:^22.1.0'

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-3.6.3.cjs
